- name: Install ansible os_stack plugin requirements
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - python-heatclient
    - python-keystoneclient
    - shade

- name: Remove stack
  os_stack:
    name: "{{ prefix }}-stack"
    state: absent
    cloud: "{{ cloud_name }}"
  ignore_errors: true
