- name: Install ansible heat_stack plugin requirements
  become: yes
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - python-heatclient
    - python-keystoneclient
    - python-novaclient
    - python-neutronclient
    - os-client-config
    - pyghmi
    - shade
    - PyYAML

- name: Deploy stack parameters template
  template:
    src=stack_parameters.j2
    dest="{{ inventory_dir }}/files/stack_parameters"

- name: Deploy stack
  os_stack:
    name: "{{ prefix }}-stack"
    state: present
    cloud: "{{ cloud_name }}"
    template: "{{ inventory_dir}}/heat_templates/ovb.yaml"
    environment: 
      - "{{ inventory_dir }}/heat_templates/resource-registry.yaml"
      -  "{{ inventory_dir }}/files/stack_parameters"
  register: stack_deployment
  ignore_errors: true

- name: Show stack deployment information
  shell: >
    export OS_USERNAME="{{ username }}";
    export OS_PASSWORD="{{ password }}";
    export OS_TENANT_NAME="{{ tenant_name }}";
    export OS_AUTH_URL="{{ auth_url }}";
    heat stack-show "{{ prefix }}-stack"
  when: stack_deployment.result is not defined

- name: set fact for undercloud floating IP address
  set_fact: 
    undercloud_floating_ip="{{ stack_deployment.stack.outputs[0].output_value }}"

- name: Create instackenv.json
  shell: >
    export OS_USERNAME="{{ username }}";
    export OS_PASSWORD="{{ password }}";
    export OS_TENANT_NAME="{{ tenant_name }}";
    export OS_AUTH_URL="{{ auth_url }}";
    {{ inventory_dir }}/files/build-nodes-json --env {{ inventory_dir }}/files/stack_parameters
